// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkPEqiL1xp1MMzgkpzEo-VeAJDjG50qk',
    appId: '1:490742211308:web:fb44d07e42ac85ffe43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    authDomain: 'wisper-74d39.firebaseapp.com',
    storageBucket: 'wisper-74d39.firebasestorage.app',
    measurementId: 'G-VSKRQYTX85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNZ0TrKbOx4GANA7xD396XcqpSFJoVDw',
    appId: '1:490742211308:android:a70790e93b547b11e43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    storageBucket: 'wisper-74d39.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkPEqiL1xp1MMzgkpzEo-VeAJDjG50qk',
    appId: '1:490742211308:web:f370e1d01473a331e43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    authDomain: 'wisper-74d39.firebaseapp.com',
    storageBucket: 'wisper-74d39.firebasestorage.app',
    measurementId: 'G-T08D5BY1M1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxgxaNXle9z0BUSdToqE0-HNRBeJVhaI',
    appId: '1:490742211308:ios:b5536bcae9072d68e43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    storageBucket: 'wisper-74d39.firebasestorage.app',
    androidClientId: '490742211308-643o4ef31gmvehmgt4anp4eak6krvcbj.apps.googleusercontent.com',
    iosClientId: '490742211308-ahh388hkmqg0msnhg4ouf4jd98830vsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisper',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxgxaNXle9z0BUSdToqE0-HNRBeJVhaI',
    appId: '1:490742211308:ios:1e2c4d2a4514ad04e43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    storageBucket: 'wisper-74d39.firebasestorage.app',
    androidClientId: '490742211308-643o4ef31gmvehmgt4anp4eak6krvcbj.apps.googleusercontent.com',
    iosClientId: '490742211308-8n1mdfpc0muet4r2j4gc97po6d50khs6.apps.googleusercontent.com',
    iosBundleId: 'com.wisperuser.userapp',
  );

}