// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtpBQ7mzu1FdYjihJ54MfAvFljyEo26x8',
    appId: '1:667291069508:web:2676f40c45418fce6ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    authDomain: 'wisper-9f2ab.firebaseapp.com',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
    measurementId: 'G-3WCVHFFGB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqGxQuw0iU0B2kDjlJM60PDgGzaYPeWIQ',
    appId: '1:488154013426:android:e1979524098e8bc2737a6b',
    messagingSenderId: '488154013426',
    projectId: 'wisper-bab8d',
    storageBucket: 'wisper-bab8d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtpBQ7mzu1FdYjihJ54MfAvFljyEo26x8',
    appId: '1:667291069508:web:d53d16431919cc236ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    authDomain: 'wisper-9f2ab.firebaseapp.com',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
    measurementId: 'G-9223XYBF42',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFfTzsfs_EQtwCQRAoRNbgPO8WXxrKfw',
    appId: '1:667291069508:ios:0a9792771c0f13766ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
    androidClientId: '667291069508-r7221dnl9halhnvt5g2el5ss7ber7p47.apps.googleusercontent.com',
    iosClientId: '667291069508-tlm46s81fi7fof0cl9b2i0um6do7sues.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisper',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2uz1ZgyG8VvXHcK5zv_ydPHdHa3l4a3I',
    appId: '1:488154013426:ios:b12401ad8e544661737a6b',
    messagingSenderId: '488154013426',
    projectId: 'wisper-bab8d',
    storageBucket: 'wisper-bab8d.firebasestorage.app',
    iosBundleId: 'com.wisperapplication.app',
  );

}