/// Options for the three community tags (Trade / Market / Category).
///
/// These strings are written verbatim into a community's `description` as
/// "Trade: X | Market: Y | Category: Z", so **renaming or removing a value
/// orphans every community already tagged with it** — the tag still renders,
/// but the edit screen can no longer re-select it. Add freely; change with care.
library;

const List<String> kTradeTypes = [
  'Local B2B',
  'Local B2C',
  'B2B Export',
  'B2C Export',
  'B2B Import',
  'B2C Import',
];

const List<String> kMarketTypes = ['Wholesale', 'Retail'];

/// Global business categories, alphabetical so the searchable dropdown reads
/// predictably. 'Other' is pinned last.
const List<String> kBusinessCategories = [
  'Accounting & Tax',
  'Actuarial Services',
  'Advertising & Media Buying',
  'Aerospace Components',
  'Agricultural Services',
  'Agriculture & Farming',
  'Agro Processing',
  'Air Conditioning & Refrigeration',
  'Aircraft Parts & Servicing',
  'Alcoholic Beverages',
  'Alternative Medicine',
  'Aluminium & Fabrication',
  'Amusement & Recreation',
  'Animal Feed',
  'Animation & VFX',
  'Apparel Manufacturing',
  'Aquaculture Equipment',
  'Architecture & Interior Design',
  'Art Galleries & Dealers',
  'Arts, Crafts & Handmade',
  'Asset Management',
  'Auctions & Liquidation',
  'Audio & Sound Equipment',
  'Automotive & Spare Parts',
  'Automotive Dealerships',
  'Automotive Repair & Servicing',
  'Aviation & Aerospace',
  'Baby Care & Maternity',
  'Bags & Luggage',
  'Bakery & Confectionery',
  'Bamboo & Rattan Products',
  'Banking & Financial Services',
  'Batteries & Power Storage',
  'Beauty & Personal Care',
  'Bedding & Home Textiles',
  'Beverage Bottling',
  'Bicycles & E-Bikes',
  'Biotechnology',
  'Blockchain & Digital Assets',
  'Boats & Marine Equipment',
  'Books & Publishing',
  'Bricks & Blocks',
  'Broadcasting & Radio',
  'Building & Construction',
  'Business Process Outsourcing',
  'Cables & Wiring',
  'Call Centre Services',
  'Candles & Home Fragrance',
  'Car Rental & Leasing',
  'Carpentry & Joinery',
  'Cash Crops & Commodities',
  'Cement & Concrete',
  'Ceramics & Pottery',
  'Chemicals & Petrochemicals',
  'Childcare Services',
  'Cinema & Film Production',
  'Civil Engineering',
  'Cleaning & Facility Management',
  'Cleaning & Household Supplies',
  'Clearing & Forwarding',
  'Cloud & Hosting Services',
  'Coffee, Tea & Cocoa',
  'Cold Chain & Refrigerated Logistics',
  'Commercial Printing',
  'Commodity Trading',
  'Computers & IT Hardware',
  'Construction Equipment Rental',
  'Consulting & Advisory',
  'Consumer Electronics',
  'Contract Manufacturing',
  'Cooperatives & Microfinance',
  'Copper & Non-Ferrous Metals',
  'Cosmetics & Skincare',
  'Cotton & Yarn',
  'Courier & Delivery',
  'Craft Beverages & Brewing',
  'Creative Agencies',
  'Crop Protection',
  'Cybersecurity',
  'Dairy Products',
  'Data & Analytics',
  'Data Centres',
  'Dental Products & Services',
  'Design & Branding',
  'Diagnostics & Imaging',
  'Digital Marketing',
  'Disability & Assistive Products',
  'Distilleries & Spirits',
  'Doors, Windows & Glass',
  'Drilling & Well Services',
  'Dry Cleaning & Laundry',
  'E-commerce & Online Retail',
  'Edible Oils & Fats',
  'Education & Training',
  'Educational Technology',
  'Electrical Contracting',
  'Electrical Equipment & Supplies',
  'Electronics & Tech',
  'Electronics Manufacturing',
  'Elevators & Escalators',
  'Embroidery & Printing',
  'Energy Consulting',
  'Engineering Services',
  'Environmental Services',
  'Event Planning & Management',
  'Exhibition & Trade Shows',
  'Facility Security Systems',
  'Farm Machinery & Equipment',
  'Fashion & Clothing',
  'Fertilizers & Agrochemicals',
  'Film & Video Production',
  'Fire Safety Equipment',
  'Fisheries & Aquaculture',
  'Fitness & Wellness Products',
  'Flooring & Carpets',
  'Florists & Landscaping',
  'Food & Beverages',
  'Food Processing Equipment',
  'Footwear',
  'Foreign Exchange & Remittance',
  'Forestry & Logging',
  'Foundries & Casting',
  'Fragrances & Perfumes',
  'Freight Forwarding',
  'Fruits & Vegetables',
  'Fuel Distribution',
  'Furniture & Home Décor',
  'Furniture Manufacturing',
  'Gaming & Esports',
  'Garden & Outdoor',
  'Gas Distribution & LPG',
  'Generators & Power Systems',
  'Geology & Surveying',
  'Gifts & Souvenirs',
  'Glass Manufacturing',
  'Gold & Precious Metals',
  'Grains & Cereals',
  'Graphic Design',
  'Greenhouses & Hydroponics',
  'Grocery & Provisions',
  'Hair Products & Extensions',
  'Handicrafts & Artisan Goods',
  'Hardware Stores',
  'Health & Pharmaceuticals',
  'Healthcare Services',
  'Heavy Machinery & Earthmoving',
  'Herbal & Traditional Medicine',
  'Home Appliances',
  'Home Improvement & Renovation',
  'Horticulture & Nursery',
  'Hospital Equipment & Supplies',
  'Hospitality & Hotels',
  'Human Resources & Recruitment',
  'HVAC Systems',
  'Ice & Cold Storage',
  'Import & Export Services',
  'Industrial Automation',
  'Industrial Equipment',
  'Industrial Gases',
  'Information Technology Services',
  'Infrastructure Development',
  'Insurance',
  'Interior Fit-Out',
  'Internet Service Providers',
  'Investment & Private Equity',
  'Irrigation Systems',
  'IT Support & Managed Services',
  'Janitorial Supplies',
  'Jewellery & Watches',
  'Kitchenware & Tableware',
  'Laboratory Supplies',
  'Land Surveying',
  'Leather & Leather Goods',
  'Legal Services',
  'Lighting & Fixtures',
  'Livestock & Poultry',
  'Logistics & Freight',
  'Lubricants & Oils',
  'Machine Tools',
  'Manufacturing & Fabrication',
  'Marine & Boats',
  'Maritime Services',
  'Marketing & Advertising',
  'Meat & Seafood Processing',
  'Media & Entertainment',
  'Medical Equipment & Devices',
  'Metals & Alloys',
  'Mining & Minerals',
  'Mobile Money & Fintech',
  'Mobile Phones & Accessories',
  'Motorcycles & Tricycles',
  'Moulds & Dies',
  'Movers & Relocation',
  'Music & Recording',
  'Musical Instruments',
  'Networking Equipment',
  'Non-Profit & NGO',
  'Nutraceuticals & Supplements',
  'Office Furniture & Equipment',
  'Oil & Gas',
  'Optical & Eyewear',
  'Organic & Natural Products',
  'Outdoor & Camping Gear',
  'Packaging & Printing',
  'Paints & Coatings',
  'Paper & Pulp',
  'Payment Processing',
  'Personal Protective Equipment',
  'Pest Control',
  'Pet Supplies & Veterinary',
  'Petroleum Products',
  'Pharmaceutical Manufacturing',
  'Photography & Videography',
  'Pipes & Fittings',
  'Plant Hire',
  'Plastics & Rubber',
  'Plumbing & Sanitary Ware',
  'Ports & Terminals',
  'Poultry Equipment',
  'Power Generation',
  'Precision Engineering',
  'Printing & Signage',
  'Procurement Services',
  'Professional Training',
  'Property Development',
  'Property Management',
  'Public Relations',
  'Publishing & Print Media',
  'Pumps & Valves',
  'Quarrying & Aggregates',
  'Radio & Communication Equipment',
  'Rail Transport',
  'Real Estate & Property',
  'Recycling & Waste Management',
  'Religious & Ceremonial Goods',
  'Renewable Energy',
  'Research & Development',
  'Restaurants & Catering',
  'Retail & Supermarkets',
  'Rice Milling & Processing',
  'Roofing Materials',
  'Rubber Products',
  'Safety & Industrial Supplies',
  'Salon & Spa Equipment',
  'Sanitation & Water Treatment',
  'Scaffolding & Formwork',
  'Scrap & Recycling Trade',
  'Seaweed & Marine Products',
  'Security & Surveillance',
  'Security Services',
  'Seeds & Seedlings',
  'Semiconductors',
  'Sewing & Tailoring',
  'Shipbuilding & Repair',
  'Shipping & Customs Clearing',
  'Signage & Branding',
  'Social Media Services',
  'Software & IT Services',
  'Solar Panels & Energy',
  'Solid Minerals',
  'Spices & Seasonings',
  'Sports & Fitness',
  'Sports Equipment Manufacturing',
  'Stationery & Office Supplies',
  'Steel & Metal Products',
  'Storage & Self-Storage',
  'Sugar & Sweeteners',
  'Surveying Equipment',
  'Tailoring & Bespoke Fashion',
  'Tanneries & Hides',
  'Tea & Herbal Infusions',
  'Telecommunications Equipment',
  'Telecommunications Services',
  'Textiles & Fabrics',
  'Tiles, Marble & Granite',
  'Timber & Wood Products',
  'Tobacco Products',
  'Tools & Hardware',
  'Tourism Services',
  'Toys & Baby Products',
  'Trading & Commodities',
  'Traditional & Cultural Wear',
  'Translation & Language Services',
  'Transportation & Ride Services',
  'Travel & Tourism',
  'Tyres & Batteries',
  'Uniforms & Workwear',
  'Utilities',
  'Vehicle Parts Manufacturing',
  'Vehicles & Trucks',
  'Vending & Kiosks',
  'Veterinary Services',
  'Warehousing & Storage',
  'Waste Collection',
  'Watches & Accessories',
  'Water & Beverage Production',
  'Water Drilling & Boreholes',
  'Web & Mobile Development',
  'Welding & Machining',
  'Wellness & Spa Services',
  'Wholesale & Distribution',
  'Wind Energy',
  'Wine & Spirits Trade',
  'Wire & Mesh Products',
  'Woodworking Machinery',
  'Writing & Content Services',
  'Other',
];
